/*
 * $Id: keydef.c,v 1.9 2001/10/01 13:23:18 jonas Exp $
 *
 */

#include <getkw.h>

BEGIN_SECTION(main_opt)
	KEYWORD("title", STRING, OPTIONAL)
	KEYWORD("nprint", INT, OPTIONAL)
	KEYWORD("Jmax", INT, REQUIRED)
	KEYWORD("file", STRING, OPTIONAL)
	KEYWORD("manifold", INT, OPTIONAL)
	KEYWORD("terminal", INT, OPTIONAL)
END_SECTION

BEGIN_SECTION(mol_opt)
	KEYWORD("A", DOUBLE, OPTIONAL)
	KEYWORD("B", DOUBLE, REQUIRED)
	KEYWORD("C", DOUBLE, OPTIONAL)
END_SECTION

BEGIN_SECTION(pot_opt)
	KEYWORD("Vj", DOUBLE, OPTIONAL)
	KEYWORD("Vk", DOUBLE, OPTIONAL)
	KEYWORD("Vm", DOUBLE, OPTIONAL)
END_SECTION

BEGIN_SECTION(mom_opt)
	KEYWORD("nmom", INT, OPTIONAL)
	KEYWORD("spectrum", INT, OPTIONAL)
	KEYWORD("cm1", DOUBLE, OPTIONAL)
	KEYWORD("T", DOUBLE, OPTIONAL)
	KEYWORD("gauss_exp", DOUBLE, OPTIONAL)
	KEYWORD("linestep", DOUBLE, OPTIONAL)
END_SECTION

BEGIN_SECTION(loop_opt)
	KEYWORD("Jmax", INT, OPTIONAL)
	KEYWORD("Vj", DOUBLE, OPTIONAL)
	KEYWORD("Vk", DOUBLE, OPTIONAL)
	KEYWORD("Vm", DOUBLE, OPTIONAL)
	KEYWORD("T", DOUBLE, OPTIONAL)
	KEYWORD("manifold", INT, OPTIONAL)
END_SECTION

BEGIN_SECTION(hinda_rot)
	KEYWORD("title", STRING, OPTIONAL)
	KEYWORD("nprint", INT, OPTIONAL)
	KEYWORD("Jmax", INT, REQUIRED)
	KEYWORD("file", STRING, OPTIONAL)
	KEYWORD("manifold", INT, OPTIONAL)
	KEYWORD("terminal", INT, OPTIONAL)
	SECTION("POTENTIAL", EMPTY, OPTIONAL, pot_opt)
	SECTION("MOLECULE", EMPTY, REQUIRED, mol_opt)
	SECTION("MOMENTS", INT, HAS_ARG|OPTIONAL, mom_opt)
	SECTION("LOOP", INT, HAS_ARG|OPTIONAL, loop_opt)
END_SECTION

BEGIN_SECTION(sections)
	SECTION("HINDAROT", EMPTY, REQUIRED, hinda_rot)
END_SECTION

MAIN_SECTION(sections)

